Autogenerated tree updates.
merged:

  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: a8236c00f3724b661ace2bd2626ae7fb10dbf05e
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 6fc9801e97e4465e99c9a86f85d7fcdbaa176996

diff --git a/net-print/cups/templates/cups.tmpl b/net-print/cups/templates/cups.tmpl
--- a/net-print/cups/templates/cups.tmpl
+++ b/net-print/cups/templates/cups.tmpl
@@ -1,38 +1,35 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=7
 
-PYTHON_COMPAT=( python2_7 )
+inherit autotools linux-info xdg multilib-minimal optfeature pam toolchain-funcs
 
-inherit autotools flag-o-matic linux-info xdg multilib-minimal pam python-single-r1 user java-pkg-opt-2 systemd toolchain-funcs
+MY_PV="${PV/_beta/b}"
+MY_PV="${MY_PV/_rc/rc}"
+MY_PV="${MY_PV/_p/op}"
+MY_P="${PN}-${MY_PV}"
 
-MY_P="${P/_rc/rc}"
-MY_P="${MY_P/_beta/b}"
-MY_PV="${PV/_rc/rc}"
-MY_PV="${MY_PV/_beta/b}"
+SRC_URI="{{src_uri}}"
+KEYWORDS="*"
 
-if [[ ${PV} == *9999 ]]; then
-	inherit git-r3
-	EGIT_REPO_URI="https://github.com/apple/cups.git"
-	if [[ ${PV} != 9999 ]]; then
-		EGIT_BRANCH=branch-${PV/.9999}
-	fi
-else
-	#SRC_URI="https://github.com/apple/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"
-	SRC_URI="https://github.com/apple/cups/releases/download/v${PV}/${P}-source.tar.gz"
-	KEYWORDS="alpha amd64 arm arm64 hppa ia64 ~mips ppc ppc64 s390 ~sh sparc x86 ~amd64-fbsd ~x86-fbsd ~m68k-mint"
-fi
+S="${WORKDIR}/${MY_P}"
 
 DESCRIPTION="The Common Unix Printing System"
-HOMEPAGE="https://www.cups.org/"
+HOMEPAGE="https://www.cups.org/ https://github.com/OpenPrinting/cups"
 
-LICENSE="GPL-2"
+LICENSE="Apache-2.0"
 SLOT="0"
-IUSE="acl dbus debug java kerberos lprng-compat pam python selinux +ssl static-libs systemd +threads usb X xinetd zeroconf"
+IUSE="acl dbus debug kerberos openssl pam selinux +ssl static-libs systemd test usb X xinetd zeroconf"
 
-CDEPEND="
-	app-text/libpaper
+# As of 2.4.2, they don't actually seem to be interactive (they pass some flags
+# by default to input for us), but they fail on some greyscale issue w/ poppler?
+RESTRICT="!test? ( test ) test"
+
+BDEPEND="
+	virtual/pkgconfig
+"
+DEPEND="
+	app-text/libpaper:=
 	sys-libs/zlib
 	acl? (
 		kernel_linux? (
@@ -41,45 +38,28 @@ CDEPEND="
 		)
 	)
 	dbus? ( >=sys-apps/dbus-1.6.18-r1[${MULTILIB_USEDEP}] )
-	java? ( >=virtual/jre-1.6:* )
 	kerberos? ( >=virtual/krb5-0-r1[${MULTILIB_USEDEP}] )
-	!lprng-compat? ( !net-print/lprng )
-	pam? ( virtual/pam )
-	python? ( ${PYTHON_DEPS} )
-	ssl? ( >=net-libs/gnutls-2.12.23-r6:0=[${MULTILIB_USEDEP}] )
+	pam? ( sys-libs/pam )
+	!pam? ( virtual/libcrypt:= )
+	ssl? (
+		!openssl? ( >=net-libs/gnutls-2.12.23-r6:0=[${MULTILIB_USEDEP}] )
+		openssl? ( dev-libs/openssl:=[${MULTILIB_USEDEP}] )
+	)
 	systemd? ( sys-apps/systemd )
 	usb? ( virtual/libusb:1 )
 	X? ( x11-misc/xdg-utils )
 	xinetd? ( sys-apps/xinetd )
-	zeroconf? ( >=net-dns/avahi-0.6.31-r2[${MULTILIB_USEDEP}] )
+	zeroconf? ( >=net-dns/avahi-0.6.31-r2[dbus,${MULTILIB_USEDEP}] )
 "
-
-DEPEND="${CDEPEND}"
-BDEPEND="
-	>=virtual/pkgconfig-0-r1[${MULTILIB_USEDEP}]
-"
-
-RDEPEND="${CDEPEND}
+RDEPEND="
+	${DEPEND}
 	selinux? ( sec-policy/selinux-cups )
 "
-
 PDEPEND=">=net-print/cups-filters-1.0.43"
 
-REQUIRED_USE="
-	python? ( ${PYTHON_REQUIRED_USE} )
-	usb? ( threads )
-"
-
-# upstream includes an interactive test which is a nono for gentoo
-RESTRICT="test"
-
-# systemd-socket.patch from Fedora
 PATCHES=(
-	"${FILESDIR}/${PN}-2.2.0-dont-compress-manpages.patch"
-	"${FILESDIR}/${PN}-2.2.6-fix-install-perms.patch"
-	"${FILESDIR}/${PN}-1.4.4-nostrip.patch"
-	"${FILESDIR}/${PN}-2.0.2-rename-systemd-service-files.patch"
-	"${FILESDIR}/${PN}-2.0.1-xinetd-installation-fix.patch"
+	"${FILESDIR}/${PN}-2.4.1-nostrip.patch"
+	"${FILESDIR}/${PN}-2.4.1-user-AR.patch"
 )
 
 MULTILIB_CHOST_TOOLS=(
@@ -91,15 +71,13 @@ pkg_setup() {
 	enewuser lp -1 -1 -1 lp
 	enewgroup lpadmin 106
 
-	use python && python-single-r1_pkg_setup
-
 	if use kernel_linux; then
 		linux-info_pkg_setup
 		if  ! linux_config_exists; then
 			ewarn "Can't check the linux kernel configuration."
 			ewarn "You might have some incompatible options enabled."
 		else
-			# recheck that we don't have usblp to collide with libusb; this should now work in most cases (bug 501122)
+			# Recheck that we don't have usblp to collide with libusb; this should now work in most cases (bug #501122)
 			if use usb; then
 				if linux_chkconfig_present USB_PRINTER; then
 					elog "Your USB printers will be managed via libusb. In case you run into problems, "
@@ -128,27 +106,21 @@ pkg_setup() {
 src_prepare() {
 	default
 
-	# Remove ".SILENT" rule for verbose output (bug 524338).
+	# Remove ".SILENT" rule for verbose output (bug #524338).
 	sed 's#^.SILENT:##g' -i "${S}"/Makedefs.in || die "sed failed"
 
-	# Fix install-sh, posix sh does not have 'function'.
-	sed 's#function gzipcp#gzipcp()#g' -i "${S}/install-sh"
+	AT_M4DIR="config-scripts" eautoreconf
 
-	AT_M4DIR=config-scripts eaclocal
-	eautoconf
-
-	# custom Makefiles
+	# Custom Makefiles
 	multilib_copy_sources
 }
 
 multilib_src_configure() {
 	export DSOFLAGS="${LDFLAGS}"
 
-	einfo LINGUAS=\"${LINGUAS}\"
-
-	# explicitly specify compiler wrt bug 524340
+	# Explicitly specify compiler wrt bug #524340
 	#
-	# need to override KRB5CONFIG for proper flags
+	# Need to override KRB5CONFIG for proper flags
 	# https://github.com/apple/cups/issues/4423
 	local myeconfargs=(
 		CC="$(tc-getCC)"
@@ -156,34 +128,48 @@ multilib_src_configure() {
 		KRB5CONFIG="${EPREFIX}"/usr/bin/${CHOST}-krb5-config
 		--libdir="${EPREFIX}"/usr/$(get_libdir)
 		--localstatedir="${EPREFIX}"/var
+		# Follow Fedora permission setting
+		--with-cupsd-file-perm=0755
 		--with-exe-file-perm=755
+		--with-log-file-perm=0640
+		# Used by Debian, also prevents printers from getting
+		# disabled and users not knowing how to re-enable them
+		--with-error-policy=retry-job
+		# Used in Debian and Fedora
+		--enable-sync-on-close
+		#
 		--with-rundir="${EPREFIX}"/run/cups
+		--with-pkgconfpath="${EPREFIX}"/usr/$(get_libdir)/pkgconfig
 		--with-cups-user=lp
 		--with-cups-group=lp
 		--with-docdir="${EPREFIX}"/usr/share/cups/html
-		--with-languages="${LINGUAS}"
-		--with-system-groups=lpadmin
+		# See bug #863221 for adding root
+		--with-system-groups="root lpadmin"
 		--with-xinetd="${EPREFIX}"/etc/xinetd.d
 		$(multilib_native_use_enable acl)
 		$(use_enable dbus)
 		$(use_enable debug)
 		$(use_enable debug debug-guards)
 		$(use_enable debug debug-printfs)
-		$(multilib_native_use_with java)
 		$(use_enable kerberos gssapi)
 		$(multilib_native_use_enable pam)
-		$(multilib_native_use_with python python "${PYTHON}")
 		$(use_enable static-libs static)
-		$(use_enable threads)
-		$(use_enable ssl gnutls)
-		$(use_enable systemd)
+		$(use_enable test unit-tests)
+		# USE="ssl" => gnutls
+		# USE="ssl openssl" => openssl
+		$(use_with ssl tls $(usex openssl openssl gnutls))
+		$(use_with systemd ondemand systemd)
 		$(multilib_native_use_enable usb libusb)
-		$(use_enable zeroconf avahi)
-		--disable-dnssd
-		--without-perl
-		--without-php
+		$(use_with zeroconf dnssd avahi)
 		$(multilib_is_native_abi && echo --enable-libpaper || echo --disable-libpaper)
 	)
+
+	# Handle empty LINGUAS properly, bug #771162
+	if [[ -n "${LINGUAS+x}" ]] ; then
+		myeconfargs+=(
+			--with-languages="${LINGUAS}"
+		)
+	fi
 
 	if tc-is-static-only; then
 		myeconfargs+=(
@@ -191,15 +177,17 @@ multilib_src_configure() {
 		)
 	fi
 
+	# Install in /usr/libexec always, instead of using /usr/lib/cups, as that
+	# makes more sense when facing multilib support.
+	sed -i -e 's:CUPS_SERVERBIN="$exec_prefix/lib/cups":CUPS_SERVERBIN="$exec_prefix/libexec/cups":g' configure ||die
+
 	econf "${myeconfargs[@]}"
 
-	# install in /usr/libexec always, instead of using /usr/lib/cups, as that
-	# makes more sense when facing multilib support.
 	sed -i -e "s:SERVERBIN.*:SERVERBIN = \"\$\(BUILDROOT\)${EPREFIX}/usr/libexec/cups\":" Makedefs || die
 	sed -i -e "s:#define CUPS_SERVERBIN.*:#define CUPS_SERVERBIN \"${EPREFIX}/usr/libexec/cups\":" config.h || die
 	sed -i -e "s:cups_serverbin=.*:cups_serverbin=\"${EPREFIX}/usr/libexec/cups\":" cups-config || die
 
-	# additional path corrections needed for prefix, see bug 597728
+	# Additional path corrections needed for prefix, see bug #597728
 	sed \
 		-e "s:ICONDIR.*:ICONDIR = ${EPREFIX}/usr/share/icons:" \
 		-e "s:INITDIR.*:INITDIR = ${EPREFIX}/etc:" \
@@ -217,6 +205,12 @@ multilib_src_compile() {
 }
 
 multilib_src_test() {
+	# Avoid using /tmp
+	export CUPS_TESTBASE="${T}"/cups-tests
+
+	mkdir "${T}"/cups-tests || die
+
+	# We only build some of CUPS for multilib, so can't run the tests.
 	multilib_is_native_abi && default
 }
 
@@ -232,45 +226,42 @@ multilib_src_install() {
 multilib_src_install_all() {
 	dodoc {CHANGES,CREDITS,README}.md
 
-	# move the default config file to docs
+	# Move the default config file to docs
 	dodoc "${ED}"/etc/cups/cupsd.conf.default
-	rm -f "${ED}"/etc/cups/cupsd.conf.default
+	rm -f "${ED}"/etc/cups/cupsd.conf.default || die
 
-	# clean out cups init scripts
-	rm -rf "${ED}"/etc/{init.d/cups,rc*,pam.d/cups}
+	# Clean out cups init scripts
+	rm -rf "${ED}"/etc/{init.d/cups,rc*} || die
 
-	# install our init script
-	local neededservices
-	use zeroconf && neededservices+=" avahi-daemon"
-	use dbus && neededservices+=" dbus"
-	[[ -n ${neededservices} ]] && neededservices="need${neededservices}"
-	cp "${FILESDIR}"/cupsd.init.d-r3 "${T}"/cupsd || die
-	sed -i \
-		-e "s/@neededservices@/${neededservices}/" \
-		"${T}"/cupsd || die
+	# Install our init script
+	local neededservices=(
+		$(usex zeroconf avahi-daemon '')
+		$(usex dbus dbus '')
+	)
+	[[ -n ${neededservices[@]} ]] && neededservices="need ${neededservices[@]}"
+	cp "${FILESDIR}"/cupsd.init.d-r4 "${T}"/cupsd || die
+	sed -i -e "s/@neededservices@/${neededservices}/" "${T}"/cupsd || die
 	doinitd "${T}"/cupsd
 
-	# install our pam script
-	pamd_mimic_system cups auth account
-
-	if use xinetd ; then
-		# correct path
-		sed -i \
-			-e "s:server = .*:server = /usr/libexec/cups/daemon/cups-lpd:" \
-			"${ED}"/etc/xinetd.d/cups-lpd || die
-		# it is safer to disable this by default, bug #137130
-		grep -w 'disable' "${ED}"/etc/xinetd.d/cups-lpd || \
-			{ sed -i -e "s:}:\tdisable = yes\n}:" "${ED}"/etc/xinetd.d/cups-lpd || die ; }
-		# write permission for file owner (root), bug #296221
-		fperms u+w /etc/xinetd.d/cups-lpd || die "fperms failed"
-	else
-		# always configure with --with-xinetd= and clean up later,
-		# bug #525604
-		rm -rf "${ED}"/etc/xinetd.d
+	if use pam ; then
+		rm "${ED}"/etc/pam.d/${PN} || die
+		pamd_mimic_system cups auth account
 	fi
 
-	keepdir /usr/libexec/cups/driver /usr/share/cups/{model,profiles} \
-		/var/log/cups /var/spool/cups/tmp
+	if use xinetd ; then
+		# Correct path
+		sed -i -e "s:server = .*:server = /usr/libexec/cups/daemon/cups-lpd:" \
+			"${ED}"/etc/xinetd.d/cups-lpd || die
+		# It is safer to disable this by default, bug #137130
+		grep -w 'disable' "${ED}"/etc/xinetd.d/cups-lpd || \
+			{ sed -i -e "s:}:\tdisable = yes\n}:" "${ED}"/etc/xinetd.d/cups-lpd || die ; }
+		# Write permission for file owner (root), bug #296221
+		fperms u+w /etc/xinetd.d/cups-lpd || die "fperms failed"
+	else
+		# Always configure with --with-xinetd= and clean up later,
+		# bug #525604
+		rm -rf "${ED}"/etc/xinetd.d || die
+	fi
 
 	keepdir /etc/cups/{interfaces,ppd,ssl}
 
@@ -278,58 +269,43 @@ multilib_src_install_all() {
 		rm -r "${ED}"/usr/share/applications || die
 	fi
 
-	# create /etc/cups/client.conf, bug #196967 and #266678
+	# Create /etc/cups/client.conf, bug #196967 and bug #266678
 	echo "ServerName ${EPREFIX}/run/cups/cups.sock" >> "${ED}"/etc/cups/client.conf
 
-	# the following file is now provided by cups-filters:
+	# The following file is now provided by cups-filter:
 	rm -r "${ED}"/usr/share/cups/banners || die
 
-	# the following are created by the init script
-	rm -r "${ED}"/var/cache/cups || die
+	# The following are created by the init script
+	rm -r "${ED}"/var/cache || die
 	rm -r "${ED}"/run || die
 
-	# for the special case of running lprng and cups together, bug 467226
-	if use lprng-compat ; then
-		rm -fv "${ED}"/usr/bin/{lp*,cancel}
-		rm -fv "${ED}"/usr/sbin/lp*
-		rm -fv "${ED}"/usr/share/man/man1/{lp*,cancel*}
-		rm -fv "${ED}"/usr/share/man/man8/lp*
-		ewarn "Not installing lp... binaries, since the lprng-compat useflag is set."
-		ewarn "Unless you plan to install an exotic server setup, you most likely"
-		ewarn "do not want this. Disable the useflag then and all will be fine."
-	fi
-}
-
-pkg_preinst() {
-	xdg_pkg_preinst
+	keepdir /usr/libexec/cups/driver /usr/share/cups/{model,profiles} /var/log/cups /var/spool/cups/tmp
 }
 
 pkg_postinst() {
 	# Update desktop file database and gtk icon cache (bug 370059)
 	xdg_pkg_postinst
-
 	local v
 
 	for v in ${REPLACING_VERSIONS}; do
 		if ! ver_test ${v} -ge 2.2.2-r2 ; then
-			echo
 			ewarn "The cupsd init script switched to using pidfiles. Shutting down"
 			ewarn "cupsd will fail the next time. To fix this, please run once as root"
 			ewarn "   killall cupsd ; /etc/init.d/cupsd zap ; /etc/init.d/cupsd start"
-			echo
 			break
 		fi
 	done
 
 	for v in ${REPLACING_VERSIONS}; do
-		echo
+		elog
 		elog "For information about installing a printer and general cups setup"
 		elog "take a look at: https://wiki.gentoo.org/wiki/Printing"
-		echo
 		break
 	done
-}
 
+	optfeature_header "CUPS may need installing the following for certain features to work:"
+	use zeroconf && optfeature "local hostname resolution using a hostname.local naming scheme" sys-auth/nss-mdns
+}
 pkg_postrm() {
 	# Update desktop file database and gtk icon cache (bug 370059)
 	xdg_pkg_postrm
